### ISSUE TITLE
Cannot create x.509 credentials with the SDK

### ISSUE THREAD

**Issue by nicolasgendron** [soracom/soracom-sdk-go#18]
It seems than just changing the definition of the Credentials struct for the following one will do the job.

`
type Credentials struct {
	AccessKeyId     string `json:"accessKeyId,omitempty"`
	SecretAccessKey string `json:"secretAccessKey,omitempty"`

	// x509 - related
	Certificate          string `json:"cert,omitempty"`
	PrivateKey           string `json:"key,omitempty"`
	CertificateAuthority string `json:"ca,omitempty"`
}`

Would that be something feasible to change the SDK or, if this is not an good solution, to provide one please?

Kind regards,

-Nicolas Gendron

**Comment by bearmini** [comment]
@nicolasgendron Thank you for your feedback. Could you please create a pull request with the change?

We will review it and then merge it to master.

**Comment by nicolasgendron** [comment]
I would like to, but it seems I cannot create a branch on the repository to push my change and do a pull request ... 
![image](https://user-images.githubusercontent.com/23682637/79453712-0d2d3d00-7fb8-11ea-97b1-70bd4654b5f8.png)

**Comment by 0x6b** [comment]
@nicolasgendron Yes, due to permission setting you cannot create a new branch or push your change to this repo directly. If you don't mind I will open a new pull request for you. Let me know your thoughts. Thanks!

**Comment by nicolasgendron** [comment]
What about you create a branch that I can push my changes to and then create a push request from this branch to the master?

**Comment by 0x6b** [comment]
@nicolasgendron sorry for delay on my end. Unfortunatelly we can't create a branch which you can push your changes directly. Could you fork this repo, clone your fork locally, make desired changes, push it to your fork, then create a pull request for us? Please review [Creating a pull request from a fork - GitHub Help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) for more details. Thank you.
